defaults:
  - default.yaml

optimizer:
  lr: 2e-5 # experimental use

model:
  _target_: src.models.components.multi_vector.ColBERT
  bert_name_or_module: distilbert-base-uncased
  similarity_fn: l2

train_loss:
  _target_: src.losses.single.MarginDistillationLoss
