# path to data directory
beir_dir: /workspace/beir
gpl_dir: /workspace/gpl
m2m_dir: /workspace/m2m
atds_dir: /workspace/atds
ramda_dir: /workspace/ramda
rerank_dir: /workspace/rerank
dada_dir: /workspace/dada
hyde_dir: /workspace/hyde

tmp_dir: /workspace/tmp

# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
